### ISSUE TITLE
Connection failure with NGIMU

### ISSUE THREAD

**Issue by Ferdanielhg** [xioTechnologies/NGIMU-MATLAB-Real-Time-Example#5]
Hello,

I want to connect my NGIMU through wifi, Here you can see my settings and the error message.
![image](https://user-images.githubusercontent.com/44076322/95271092-44a7d400-07fa-11eb-966d-05e7a5dc1dda.png)

![image](https://user-images.githubusercontent.com/44076322/95271074-335ec780-07fa-11eb-955b-49945851b7d0.png)

![image](https://user-images.githubusercontent.com/44076322/95271132-5db08500-07fa-11eb-8997-c2fd62cd7183.png)

Am I doing the connection correctly?

**Comment by xioTechnologies** [comment]
If you are receiving the "/sync" message then you must be listening to port 9000.  If you want to receive NGIMU data then you must listen to port 8058 (according to your screenshot).

**Comment by Ferdanielhg** [comment]
![image](https://user-images.githubusercontent.com/44076322/95358198-05bf6000-0886-11eb-99e2-3736780a758d.png)

Problem solved.
I had the NGIMU GUI software open while trying to connect to the port 8085.
Once I closed the NGIMU GUI the Matlab code ran normally.

Thanks for the help!
