### ISSUE TITLE
Connection Error {solved}

### ISSUE THREAD

**Issue by WalkingFritsie** [xioTechnologies/NGIMU-MATLAB-Real-Time-Example#7]
Hi,

I seem to have a problem with connecting the NGIMU to MATLAB (2018a).
The imu works like a charm when im using the NGIMU Gui application provided bij Xiotechnologies, but for some reason im unable to connect it to the matlab example. 

I keep getting this error (also, see Screenshot):

Warning: Unhandled OSC adress Recieved: /rssi
Warning: Invalid callback: Unhandled OSC adress Recieved: /rssi
> In instrcb (line 54)

At first i thought it was a connection error between the imu and my computer, but like mentioned earlier, that works excellent.
I also like to mention that when the imu is connected to the NGIMU Gui application provided bij Xiotechnologies, Matlab gives me an error that says the IMU is already connected to an application. does this mean that the IMU is already connected to Matlab?

I hope you'll be able to help me out!

![matlab 1](https://user-images.githubusercontent.com/102286527/159873888-bf5f091e-d1a3-4310-91ca-d6cdb48d1dfa.png)

**Comment by xioTechnologies** [comment]
The warnings are generated by the code [(line 211 of gui.m)](https://github.com/xioTechnologies/NGIMU-MATLAB-Real-Time-Example/blob/master/gui.m#L211) because handling of those messages is not yet implemented.  The example is provided as a starting point for those wishing to use MATLAB for real-time data.  If you do not intend to use the unhandled messages then I suggest you comment out the warning in the code.

**Comment by WalkingFritsie** [comment]
Thank you for the Quick reply! that clears alot of things up.
the buffer error seems to be gone now.

Unfortunately that also bring a new problem.
I get this error (Screenshot):

Error while evaluating TimerFcn for Timer 'timer-1'
Input is not a valid rigid transformation.

i hope you'll be able to help me.



![Matlab 2](https://user-images.githubusercontent.com/102286527/159893974-860f35d8-c0e0-44bd-acce-10f50488004d.png)

**Comment by xioTechnologies** [comment]
The example is provided on the assumption that users are already familiar with MATLAB and will be able understand and build on the code provided.  The error message you have shown occurs within a try/catch.  If you wish to handle this error differently then you will need to modify the code.

**Comment by WalkingFritsie** [comment]
Found the problem. 

Apparently it had something to do with the Quaternion handles,
Messed around with the script a little, and got it to work.
